### ISSUE TITLE
此脚本对繁体中文页面支持不够友好

### ISSUE THREAD

**Issue by Nigel-NI** [709924470/pixiv_fanbox_downloader#1]
Pixiv的语言设置为“繁体中文”的时候，脚本无法正常工作；曾尝试把脚本中的“点赞”换成“按讃”，并没有什么变化。
因为个人原因不方便把语言设置成“简体中文”，还请开发者早日适配繁体中文页面，非常感谢！如有叨扰，还望海涵！

**Comment by 709924470** [comment]
了解，近期会修复，感谢反馈！

**Comment by 709924470** [comment]
> Pixiv的语言设置为“繁体中文”的时候，脚本无法正常工作；曾尝试把脚本中的“点赞”换成“按讃”，并没有什么变化。
> 因为个人原因不方便把语言设置成“简体中文”，还请开发者早日适配繁体中文页面，非常感谢！如有叨扰，还望海涵！

已修复可能存在的问题, 请更新至最新版本以测试效果, 不管成功与否, 都请给予反馈,谢谢!

**Comment by Nigel-NI** [comment]
恐怕没什么变化，依旧没有下载按钮╮(╯_╰)╭

**Comment by 709924470** [comment]
我再改改

**Comment by 709924470** [comment]
> 恐怕没什么变化，依旧没有下载按钮╮(╯_╰)╭

上次忘记去掉只匹配`点赞`了, 已经更改, 现在应该起作用了

**Comment by Nigel-NI** [comment]
按钮现在可以正常显示了，感谢！
