### ISSUE TITLE
使用该脚本下载的图片不是原尺寸图片

### ISSUE THREAD

**Issue by Nigel-NI** [709924470/pixiv_fanbox_downloader#2]
该脚本下载的图片只是被网站压缩过的图片，不是画师上传的高分辨率图片。
举个例子，利用脚本下载的图片中，有一张JPG图片的分辨率为1200×719，而我手动点击网站上对应的图片查看原图并下载，原图的尺寸为5304×3176，且格式为PNG。
综上，作者可以增加一个“一键下载原图”的选项吗？

**Comment by 709924470** [comment]
这两天看看

**Comment by 709924470** [comment]
是匹配的元素问题, 现在应该会直接下载原图了
