### ISSUE TITLE
经常需要重启脚本才能出现下载按钮

### ISSUE THREAD

**Issue by Nigel-NI** [709924470/pixiv_fanbox_downloader#3]
开启脚本后，第一次打开某投稿时可以显示两个下载按钮，但是打开第二个投稿的时候，按钮就都不显示了。不只是繁体中文页面上会出现这个问题，简体中文版也有这样的问题。

**Comment by 709924470** [comment]
在改了

**Comment by 709924470** [comment]
本地测试没问题了, 请更新脚本测试
