### ISSUE TITLE
现在下载按钮又不出现了

### ISSUE THREAD

**Issue by Nigel-NI** [709924470/pixiv_fanbox_downloader#4]
如题，前两天按钮还能正常出现，今天再进网站，就没有按钮出现了。怀疑是官方改了网页的源码，请修复此问题，谢谢！
问题图片：https://upload.cc/i1/2019/09/01/H4nMRQ.png

**Comment by 709924470** [comment]
已经查明问题, 官方变动了网页布局导致按钮无法出现. 马上更新版本, 感谢issue
