### ISSUE TITLE
When I press "direct download" or "download as zip", nothing happens.

### ISSUE THREAD

**Issue by weeklyshoe** [709924470/pixiv_fanbox_downloader#5]
When I press "direct download" or "download as zip", nothing happens. I am using Tampermonkey on the latest version of chrome. Do you need to be a fanbox supporter for this to work? Or is this script supposed to work for any account?

**Comment by 709924470** [comment]
Try wait for up to 10 minutes, it takes time to download all the images to local memory and download status always show up when it's already downloaded.

You can check the downloading status by pressing F12 and check `Network` tab, the waterfall graph should show there's something's loading.

**Comment by Nightvibe-Ro** [comment]
there is button, but not work......
again this error every time"[Fanbox Downloader.js] Cannot add download button!"
![캡처d](https://user-images.githubusercontent.com/55938352/65826764-92276200-e2c5-11e9-9557-7c7ab443e063.PNG)

**Comment by weeklyshoe** [comment]
> Try wait for up to 10 minutes, it takes time to download all the images to local memory and download status always show up when it's already downloaded.
> 
> You can check the downloading status by pressing F12 and check `Network` tab, the waterfall graph should show there's something's loading.

i've been waiting for a while now and nothing's been happening....what's supposed to happen when this works? what should the waterfall graph look like?

**Comment by 709924470** [comment]
> there is button, but not work......
> again this error every time"[Fanbox Downloader.js] Cannot add download button!"
> ![캡처d](https://user-images.githubusercontent.com/55938352/65826764-92276200-e2c5-11e9-9557-7c7ab443e063.PNG)

The button is already in the page, as you can see this in the console.

```
[Fanbox Downloader.js] Successfully added the button.
```

**Comment by 709924470** [comment]
> > Try wait for up to 10 minutes, it takes time to download all the images to local memory and download status always show up when it's already downloaded.
> > You can check the downloading status by pressing F12 and check `Network` tab, the waterfall graph should show there's something's loading.
> 
> i've been waiting for a while now and nothing's been happening....what's supposed to happen when this works? what should the waterfall graph look like?

The newest version has download progress in console, try it and see if it still not working.

**Comment by weeklyshoe** [comment]
> The newest version has download progress in console, try it and see if it still not working.

nothing is showing up in the console

**Comment by 709924470** [comment]
> > The newest version has download progress in console, try it and see if it still not working.
> 
> nothing is showing up in the console

There should be something like this after you click download
![Progress status](https://imgur.com/I6ckBh5.png)

**Comment by weeklyshoe** [comment]
> > > The newest version has download progress in console, try it and see if it still not working.
> > 
> > 
> > nothing is showing up in the console
> 
> There should be something like this after you click download
> ![Progress status](https://camo.githubusercontent.com/a977447a159bf4796eecfba298c647d50d0b53a9/68747470733a2f2f696d6775722e636f6d2f4936636b4268352e706e67)

but nothing is happening after i press direct download or download as zip. do i need to wait for it to appear or am i doing something wrong?

**Comment by 709924470** [comment]
> > > > The newest version has download progress in console, try it and see if it still not working.
> > > 
> > > 
> > > nothing is showing up in the console
> > 
> > 
> > There should be something like this after you click download
> > ![Progress status](https://camo.githubusercontent.com/a977447a159bf4796eecfba298c647d50d0b53a9/68747470733a2f2f696d6775722e636f6d2f4936636b4268352e706e67)
> 
> but nothing is happening after i press direct download or download as zip. do i need to wait for it to appear or am i doing something wrong?

There should be at least something like `Downloading <Image Name>.`
![Console](https://imgur.com/xjC8oDO.png)

**Comment by AndyWang1589** [comment]
![image](https://user-images.githubusercontent.com/46545759/67167683-d6f56480-f36a-11e9-9d2c-ef0b7d4d399a.png)
![image](https://user-images.githubusercontent.com/46545759/67167686-e674ad80-f36a-11e9-86ed-b3f642793047.png)

I think I found the problem, getAllImageUrl () isn't returning anything for me. Why is this?

**Comment by weeklyshoe** [comment]
![image](https://user-images.githubusercontent.com/46545759/67167683-d6f56480-f36a-11e9-9d2c-ef0b7d4d399a.png)
![image](https://user-images.githubusercontent.com/46545759/67167686-e674ad80-f36a-11e9-86ed-b3f642793047.png)

I think I found the problem, getAllImageUrl () isn't returning anything for me. Why is this?

**Comment by 709924470** [comment]
> ![image](https://user-images.githubusercontent.com/46545759/67167683-d6f56480-f36a-11e9-9d2c-ef0b7d4d399a.png)
> ![image](https://user-images.githubusercontent.com/46545759/67167686-e674ad80-f36a-11e9-86ed-b3f642793047.png)
> 
> I think I found the problem, getAllImageUrl () isn't returning anything for me. Why is this?

Try run `document.querySelectorAll("img.lazyloaded, img.lazyloading, img.lazyload")` in your console, if there's nothing returned, it the problem in the way I try to get all elements.

There should be something like this
![Console](https://imgur.com/qiMPJwq.png)

**Comment by weeklyshoe** [comment]
> Try run `document.querySelectorAll("img.lazyloaded, img.lazyloading, img.lazyload")` in your console, if there's nothing returned, it the problem in the way I try to get all elements.
> 
> There should be something like this
> ![Console](https://camo.githubusercontent.com/cd352c4d47d5fd946d0c5a9c2ba84475c9329ec0/68747470733a2f2f696d6775722e636f6d2f71694d504a77712e706e67)

this works on the artist's home page (https://www.pixiv.net/fanbox/creator/*/), but not on the page of a single post (https://www.pixiv.net/fanbox/creator/*/post/*/)

**Comment by Uscalysta** [comment]
hmm... same problem , button show up but cant download on single post fanbox (https://www.pixiv.net/fanbox/creator/*/post/*/)

i found same error at source "[Fanbox Downloader.js] Cannot add download button!"

and found this warning 

![image](https://user-images.githubusercontent.com/57065780/67635488-e93f4780-f902-11e9-9d4a-2284effde177.png)

**Comment by 709924470** [comment]
> hmm... same problem , button show up but cant download on single post fanbox ([pixiv.net/fanbox/creator/*/post/*](https://www.pixiv.net/fanbox/creator/*/post/*/))
> 
> i found same error at source "[Fanbox Downloader.js] Cannot add download button!"
> 
> and found this warning
> 
> ![image](https://user-images.githubusercontent.com/57065780/67635488-e93f4780-f902-11e9-9d4a-2284effde177.png)

That is a script need to load from external source, and its included in the comments on the top of the script.
`// @require      https://cdnjs.cloudflare.com/ajax/libs/jszip/3.2.0/jszip.min.js`

Please update to the newest version, added a new method of adding button.

**Comment by 709924470** [comment]
> > Try run `document.querySelectorAll("img.lazyloaded, img.lazyloading, img.lazyload")` in your console, if there's nothing returned, it the problem in the way I try to get all elements.
> > There should be something like this
> > ![Console](https://camo.githubusercontent.com/cd352c4d47d5fd946d0c5a9c2ba84475c9329ec0/68747470733a2f2f696d6775722e636f6d2f71694d504a77712e706e67)
> 
> this works on the artist's home page ([pixiv.net/fanbox/creator/*](https://www.pixiv.net/fanbox/creator/*/)), but not on the page of a single post ([pixiv.net/fanbox/creator/*/post/*](https://www.pixiv.net/fanbox/creator/*/post/*/))

Can you try to inspect image element in post pages and upload a screenshot of it?
You can inspect a element by right click the element and click on the `Inspect` option.
![Inspecting an element](https://imgur.com/muWeEo2.png)

**Comment by weeklyshoe** [comment]
![image](https://user-images.githubusercontent.com/55170501/67723269-e0f21580-f9b1-11e9-8ce1-16876cb559a3.png)
this is what shows up when I inspect the preview image

also, do you need to be a fan of the creator to use this script?

**Comment by 709924470** [comment]
> ![image](https://user-images.githubusercontent.com/55170501/67723269-e0f21580-f9b1-11e9-8ce1-16876cb559a3.png)
> this is what shows up when I inspect the preview image
> 
> also, do you need to be a fan of the creator to use this script?

Yes, you need to be a fan of the creator. I'm going to add a prompt for the ones try to download without subscript.
