### ISSUE TITLE
download all files into subfolder

### ISSUE THREAD

**Issue by My1** [709924470/pixiv_fanbox_downloader#6]
to avoid cluttering the download folder with countless files maybe (if possible) have the normal downlad all function download into a subfolder

**Comment by 709924470** [comment]
FYI scripts run in Chrome cannot override it's download manager to let it download all files into a certail folder else I would already done it uwu\
There's a button called ```Download as Archive```, have you tried it though\
Also you can set custom naming rule to ```$author/$title```, this will automatically create a subforlder in archive and you can just extract it as is.

(Github finally email'd me for issues uwu)

**Comment by My1** [comment]
okay, kinda sad, would be awesome if one could make a folder or an array of files with a folder name and pass that into the DL manager and it would just accept that
