### ISSUE TITLE
fanbox的域名变更为fanbox.cc，新域名中脚本不生效

### ISSUE THREAD

**Issue by Nigel-NI** [709924470/pixiv_fanbox_downloader#7]
原先的pixiv.net/fanbox现在强制跳转到fanbox.cc，但是貌似这个脚本还没有适配新域名。作者大大如果看到此消息，还请抽时间对网站的新域名进行适配，谢谢啦！

**Comment by 709924470** [comment]
已经在第一时间适配这个域名了哦, 如果没显示按钮的话试试强制刷新页面几次uwu\
我这也有的时候不显示, 目前还不清楚原因

**Comment by Nigel-NI** [comment]
啊啊，更新了一下脚本就好了，感谢！
